/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#e5e7eb",
        "on-secondary-container": "#1e3a8a",
        "on-tertiary-fixed-variant": "#78350f",
        "on-primary": "#ffffff",
        "on-primary-container": "#0f172a",
        "background": "#f9fafb",
        "on-secondary-fixed-variant": "#1d4ed8",
        "surface-tint": "#0f172a",
        "surface-container-low": "#f3f4f6",
        "on-surface-variant": "#4b5563",
        "surface-dim": "#e5e7eb",
        "on-background": "#111827",
        "tertiary": "#f59e0b",
        "surface": "#ffffff",
        "error-container": "#fee2e2",
        "secondary-fixed-dim": "#bfdbfe",
        "primary": "#0f172a",
        "secondary-fixed": "#dbeafe",
        "on-surface": "#111827",
        "on-tertiary-fixed": "#451a03",
        "on-tertiary-container": "#78350f",
        "surface-variant": "#f3f4f6",
        "surface-container": "#f9fafb",
        "surface-container-lowest": "#ffffff",
        "outline": "#d1d5db",
        "tertiary-container": "#fef3c7",
        "primary-fixed-dim": "#cbd5e1",
        "tertiary-fixed": "#fde68a",
        "primary-container": "#e2e8f0",
        "on-secondary-fixed": "#1e3a8a",
        "outline-variant": "#e5e7eb",
        "tertiary-fixed-dim": "#fcd34d",
        "inverse-on-surface": "#f9fafb",
        "secondary-container": "#dbeafe",
        "inverse-primary": "#f8fafc",
        "error": "#ef4444",
        "on-primary-fixed": "#0f172a",
        "primary-fixed": "#f1f5f9",
        "on-primary-fixed-variant": "#334155",
        "inverse-surface": "#111827",
        "on-error-container": "#7f1d1d",
        "on-error": "#ffffff",
        "surface-container-highest": "#d1d5db",
        "surface-bright": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary": "#3b82f6",
        "on-tertiary": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "unit-xs": "4px",
        "gutter": "24px",
        "container-max": "1440px",
        "unit-sm": "8px",
        "unit-lg": "24px",
        "margin-desktop": "64px",
        "unit-xl": "48px",
        "margin-mobile": "20px",
        "unit-md": "16px"
      },
      "fontFamily": {
        "label-sm": ["Geist"],
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "title-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      "fontSize": {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
