import React, { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  en: {
    // Navigation
    home: "Home",
    cart: "Cart",
    profile: "Profile",
    auctions: "Auctions",
    groupBuy: "Group Buy",
    budgetBuilder: "Budget Builder",
    localSellers: "Local Sellers",
    aiAssistant: "AI Assistant",
    login: "Sign In",
    register: "Register",
    logout: "Logout",
    aboutUs: "About Us",
    shipping: "Shipping",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    partner: "Partner Program",
    
    // Home Page
    heroTitle: "Play with Passion, Shop with Intelligence",
    heroSubtitle: "\"Success isn't just about hard work; it's about making smart choices. One8 AI matches you with the absolute best gear tailored to your budget.\"",
    brandAmbassador: "— Virat Kohli, Brand Ambassador",
    theFutureOfCommerce: "The Future of Commerce",
    askAiAssistant: "Ask AI Assistant",
    browseCatalog: "Browse Catalog",
    exploreModes: "Explore Modes",
    groupBuyDesc: "Team up with friends or the community to unlock massive wholesale discounts.",
    liveAuctions: "Live Auctions",
    liveAuctionsDesc: "Bid in real-time on exclusive, rare, and limited-edition items.",
    budgetBuilderDesc: "Input your budget and shopping items, and let AI build the best product combination.",
    aiSmartMatches: "AI Smart Matches",
    viewAll: "View All",
    match: "Match",
    priceDrops: "Price Drops",
    save: "SAVE",
    trendingNow: "Trending Now",
    
    // General UI
    searchPlaceholder: "Search products, brands, or ask AI...",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    loading: "Loading...",
    noProducts: "No products found.",
    error: "An error occurred.",
    success: "Success",
    placeOrder: "Place Order",
    subtotal: "Subtotal",
    total: "Total",
    price: "Price",
    quantity: "Quantity",
    checkout: "Checkout",
    
    // Login / Register
    email: "Email Address",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone Number",
    otpCode: "OTP Code",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    
    welcomeBack: "Welcome Back",
    signInDesc: "Sign in to continue to One8 Marketplace",
    unifiedPortal: "Unified Portal: We automatically log you in as a Buyer or Seller based on your account.",
    forgotPassword: "Forgot password?",
    signUp: "Sign up",
    createAccount: "Create Account",
    joinMarketplace: "Join One8 Marketplace to discover and sell premium goods",
    confirmPassword: "Confirm Password",
    wantTo: "I want to...",
    shop: "Shop",
    sell: "Sell",
    verifyEmail: "Verify your email address",
    otpSentText: "We have sent a 6-digit verification code to",
    otpVerificationCode: "OTP Verification Code",
    resendCode: "Resend Code",
    resending: "Resending...",
    changeEmail: "Change Email / Details",
    verifyAndRegister: "Verify & Register",
    sendVerificationOtp: "Send Verification OTP",
    
    // Cart Page
    yourCart: "Your Cart",
    cartIsEmpty: "Your cart is empty",
    cartEmptyDesc: "Looks like you haven't added any premium items yet.",
    startShopping: "Start Shopping",
    orderSummary: "Order Summary",
    calculatedAtCheckout: "Calculated at checkout",
    proceedToCheckout: "Proceed to Checkout",
    
    // Roles / Extra Navigation
    categories: "Categories",
    addProducts: "Add Products",
    adminPanel: "Admin Panel",
    footerDesc: "AI-Powered Luxury Marketplace. Curating the future of smart commerce.",
    footerRights: "© 2026 One8 AI Marketplace. All rights reserved.",
    sellerDashboard: "Seller Dashboard",
    myOrders: "My Orders",
    viewProfile: "View Profile"
  },
  ta: {
    // Tamil
    home: "முகப்பு",
    cart: "கூடை",
    profile: "சுயவிவரம்",
    auctions: "ஏலம்",
    groupBuy: "குழு கொள்முதல்",
    budgetBuilder: "பட்ஜெட் பில்டர்",
    localSellers: "உள்ளூர் விற்பனையாளர்கள்",
    aiAssistant: "AI உதவியாளர்",
    login: "உள்நுழை",
    register: "பதிவு செய்",
    logout: "வெளியேறு",
    aboutUs: "எங்களைப் பற்றி",
    shipping: "கப்பல் போக்குவரத்து",
    terms: "சேவை விதிமுறைகள்",
    privacy: "தனியுரிமைக் கொள்கை",
    partner: "கூட்டாளர் திட்டம்",
    
    // Home Page
    heroTitle: "ஆர்வத்துடன் விளையாடுங்கள், புத்திசாலித்தனத்துடன் ஷாப்பிங் செய்யுங்கள்",
    heroSubtitle: "\"வெற்றி என்பது வெறும் கடின உழைப்பு மட்டுமல்ல; அது புத்திசாலித்தனமான தேர்வுகளைச் செய்வதாகும். One8 AI உங்கள் பட்ஜெட்டுக்கு ஏற்றவாறு சிறந்த கியர்களுடன் உங்களைப் பொருத்துகிறது.\"",
    brandAmbassador: "— விராட் கோலி, பிராண்ட் தூதர்",
    theFutureOfCommerce: "வர்த்தகத்தின் எதிர்காலம்",
    askAiAssistant: "AI உதவியாளரிடம் கேளுங்கள்",
    browseCatalog: "கேடலாக்கை உலாவுக",
    exploreModes: "முறைகளை ஆராயுங்கள்",
    groupBuyDesc: "பெரிய மொத்த தள்ளுபடிகளைப் பெற நண்பர்கள் அல்லது சமூகத்துடன் இணையுங்கள்.",
    liveAuctions: "நேரடி ஏலம்",
    liveAuctionsDesc: "பிரத்தியேகமான, அரிய மற்றும் குறைந்த பதிப்பு உருப்படிகளுக்கு நிகழ்நேரத்தில் ஏலம் எடுக்கவும்.",
    budgetBuilderDesc: "உங்கள் பட்ஜெட் மற்றும் ஷாப்பிங் உருப்படிகளை உள்ளீடு செய்யுங்கள், AI சிறந்த தயாரிப்பு கலவையை உருவாக்கட்டும்.",
    aiSmartMatches: "AI ஸ்மார்ட் பொருத்தங்கள்",
    viewAll: "அனைத்தையும் காட்டு",
    match: "பொருத்தம்",
    priceDrops: "விலை வீழ்ச்சி",
    save: "சேமிப்பு",
    trendingNow: "இப்போது பிரபலமாக உள்ளது",
    
    // General UI
    searchPlaceholder: "தயாரிப்புகளைத் தேடுங்கள்...",
    addToCart: "கூடையில் சேர்",
    buyNow: "இப்போது வாங்கு",
    loading: "ஏற்றப்படுகிறது...",
    noProducts: "தயாரிப்புகள் எதுவும் கிடைக்கவில்லை.",
    error: "ஒரு பிழை ஏற்பட்டது.",
    success: "வெற்றி",
    placeOrder: "ஆர்டர் செய்",
    subtotal: "கூட்டுத்தொகை",
    total: "மொத்தம்",
    price: "விலை",
    quantity: "அளவு",
    checkout: "செக்அவுட்",
    
    // Login / Register
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    firstName: "முதல் பெயர்",
    lastName: "கடைசி பெயர்",
    phone: "தொலைபேசி எண்",
    otpCode: "OTP குறியீடு",
    sendOtp: "OTP அனுப்பு",
    verifyOtp: "OTP சரிபார்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    
    welcomeBack: "மீண்டும் வருக",
    signInDesc: "One8 சந்தையைத் தொடர உள்நுழையவும்",
    unifiedPortal: "ஒருங்கிணைந்த போர்ட்டல்: உங்கள் கணக்கின் அடிப்படையில் உங்களை வாங்குபவராக அல்லது விற்பனையாளராக தானாகவே உள்நுழைப்போம்.",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    signUp: "பதிவு செய்",
    createAccount: "கணக்கை உருவாக்கு",
    joinMarketplace: "பிரீமியம் பொருட்களைக் கண்டறியவும் விற்கவும் One8 சந்தையில் சேரவும்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    wantTo: "நான் விரும்புகிறேன்...",
    shop: "வாங்க",
    sell: "விற்க",
    verifyEmail: "உங்கள் மின்னஞ்சல் முகவரியைச் சரிபார்க்கவும்",
    otpSentText: "நாங்கள் 6 இலக்க சரிபார்ப்புக் குறியீட்டை அனுப்பியுள்ளோம்",
    otpVerificationCode: "OTP சரிபார்ப்புக் குறியீடு",
    resendCode: "குறியீட்டை மீண்டும் அனுப்பு",
    resending: "மீண்டும் அனுப்புகிறது...",
    changeEmail: "மின்னஞ்சல் / விவரங்களை மாற்றவும்",
    verifyAndRegister: "சரிபார்த்து பதிவு செய்",
    sendVerificationOtp: "சரிபார்ப்பு OTP அனுப்பு",
    
    // Cart Page
    yourCart: "உங்கள் கூடை",
    cartIsEmpty: "உங்கள் கூடை காலியாக உள்ளது",
    cartEmptyDesc: "நீங்கள் இன்னும் பிரீமியம் பொருட்கள் எதையும் சேர்க்கவில்லை எனத் தெரிகிறது.",
    startShopping: "ஷாப்பிங் செய்யத் தொடங்குங்கள்",
    orderSummary: "ஆர்டர் சுருக்கம்",
    calculatedAtCheckout: "செக்அவுட்டில் கணக்கிடப்படும்",
    proceedToCheckout: "செக்அவுட்டிற்குச் செல்லவும்",
    
    // Roles / Extra Navigation
    categories: "பிரிவுகள்",
    addProducts: "தயாரிப்புகளைச் சேர்க்கவும்",
    adminPanel: "நிர்வாக குழு",
    footerDesc: "AI-ஆற்றல் கொண்ட சொகுசு சந்தை. ஸ்மார்ட் வர்த்தகத்தின் எதிர்காலத்தை நிர்வகிக்கிறது.",
    footerRights: "© 2026 One8 AI சந்தை. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    sellerDashboard: "விற்பனையாளர் டாஷ்போர்டு",
    myOrders: "எனது ஆர்டர்கள்",
    viewProfile: "சுயவிவரத்தைக் காட்டு"
  },
  hi: {
    // Hindi
    home: "मुख्य पृष्ठ",
    cart: "कार्ट",
    profile: "प्रोफाइल",
    auctions: "नीलामी",
    groupBuy: "ग्रुप बाय",
    budgetBuilder: "बजट बिल्डर",
    localSellers: "स्थानीय विक्रेता",
    aiAssistant: "एआई सहायक",
    login: "लॉगिन",
    register: "रजिस्टर",
    logout: "लॉगआउट",
    aboutUs: "हमारे बारे में",
    shipping: "शिपिंग",
    terms: "सेवा की शर्तें",
    privacy: "गोपनीयता नीति",
    partner: "पार्टनर प्रोग्राम",
    
    // Home Page
    heroTitle: "जुनून के साथ खेलें, समझदारी से खरीदारी करें",
    heroSubtitle: "\"सफलता केवल कड़ी मेहनत के बारे में नहीं है; यह स्मार्ट विकल्प बनाने के बारे में है। One8 AI आपके बजट के अनुरूप सर्वोत्तम गियर से आपका मिलान करता है।\"",
    brandAmbassador: "— विराट कोहली, ब्रांड एंबेसडर",
    theFutureOfCommerce: "वाणिज्य का भविष्य",
    askAiAssistant: "एआई सहायक से पूछें",
    browseCatalog: "कैटलॉग ब्राउज़ करें",
    exploreModes: "मोड्स एक्सप्लोर करें",
    groupBuyDesc: "भारी थोक छूट का लाभ उठाने के लिए दोस्तों या समुदाय के साथ टीम बनाएं।",
    liveAuctions: "लाइव नीलामी",
    liveAuctionsDesc: "विशेष, दुर्लभ और सीमित-संस्करण वाली वस्तुओं पर वास्तविक समय में बोली लगाएं।",
    budgetBuilderDesc: "अपना बजट और खरीदारी की वस्तुएं दर्ज करें, और एआई को सर्वोत्तम संयोजन बनाने दें।",
    aiSmartMatches: "एआई स्मार्ट मैच",
    viewAll: "सभी देखें",
    match: "मैच",
    priceDrops: "कीमतों में गिरावट",
    save: "बचत",
    trendingNow: "अभी ट्रेंडिंग में है",
    
    // General UI
    searchPlaceholder: "उत्पाद खोजें...",
    addToCart: "कार्ट में जोड़ें",
    buyNow: "अभी खरीदें",
    loading: "लोड हो रहा है...",
    noProducts: "कोई उत्पाद नहीं मिला।",
    error: "एक त्रुटि हुई।",
    success: "सफलता",
    placeOrder: "ऑर्डर दें",
    subtotal: "उपयोग",
    total: "कुल",
    price: "कीमत",
    quantity: "मात्रा",
    checkout: "चेकआउट",
    
    // Login / Register
    email: "ईमेल पता",
    password: "पासवर्ड",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    phone: "फ़ोन नंबर",
    otpCode: "ओटीपी कोड",
    sendOtp: "ओटीपी भेजें",
    verifyOtp: "ओटीपी सत्यापित करें",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    
    welcomeBack: "स्वागत है",
    signInDesc: "One8 मार्केटप्लेस पर जारी रखने के लिए साइन इन करें",
    unifiedPortal: "एकीकृत पोर्टल: हम आपके खाते के आधार पर आपको स्वचालित रूप से एक खरीदार या विक्रेता के रूप में लॉग इन करते हैं।",
    forgotPassword: "पासवर्ड भूल गए?",
    signUp: "साइन अप",
    createAccount: "खाता बनाएं",
    joinMarketplace: "प्रीमियम वस्तुओं को खोजने और बेचने के लिए One8 मार्केटप्लेस में शामिल हों",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    wantTo: "मैं चाहता हूँ...",
    shop: "खरीदना",
    sell: "बेचना",
    verifyEmail: "अपना ईमेल पता सत्यापित करें",
    otpSentText: "हमने 6 अंकों का सत्यापन कोड भेजा है",
    otpVerificationCode: "ओटीपी सत्यापन कोड",
    resendCode: "कोड पुनः भेजें",
    resending: "पुनः भेजा जा रहा है...",
    changeEmail: "ईमेल / विवरण बदलें",
    verifyAndRegister: "सत्यापित करें और पंजीकरण करें",
    sendVerificationOtp: "सत्यापन ओटीपी भेजें",
    
    // Cart Page
    yourCart: "आपका कार्ट",
    cartIsEmpty: "आपका कार्ट खाली है",
    cartEmptyDesc: "ऐसा लगता है कि आपने अभी तक कोई प्रीमियम आइटम नहीं जोड़ा है।",
    startShopping: "खरीदारी शुरू करें",
    orderSummary: "ऑर्डर सारांश",
    calculatedAtCheckout: "चेकआउट के समय गणना की जाएगी",
    proceedToCheckout: "चेकआउट के लिए आगे बढ़ें",
    
    // Roles / Extra Navigation
    categories: "श्रेणियां",
    addProducts: "उत्पाद जोड़ें",
    adminPanel: "एडमिन पैनल",
    footerDesc: "एआई-संचालित लक्जरी मार्केटप्लेस। स्मार्ट कॉमर्स के भविष्य का संचालन।",
    footerRights: "© 2026 One8 एआई मार्केटप्लेस। सभी अधिकार सुरक्षित।",
    sellerDashboard: "विक्रेता डैशबोर्ड",
    myOrders: "मेरे आदेश",
    viewProfile: "प्रोफाइल देखें"
  },
  es: {
    // Spanish
    home: "Inicio",
    cart: "Carrito",
    profile: "Perfil",
    auctions: "Subastas",
    groupBuy: "Compra Grupal",
    budgetBuilder: "Creador de Presupuesto",
    localSellers: "Vendedores Locales",
    aiAssistant: "Asistente de IA",
    login: "Iniciar Sesión",
    register: "Registrarse",
    logout: "Cerrar Sesión",
    aboutUs: "Sobre Nosotros",
    shipping: "Envío",
    terms: "Términos de Servicio",
    privacy: "Política de Privacidad",
    partner: "Programa de Socios",
    
    // Home Page
    heroTitle: "Juega con Pasión, Compra con Inteligencia",
    heroSubtitle: "\"El éxito no se trata solo de trabajo duro; se trata de tomar decisiones inteligentes. One8 AI le ofrece el mejor equipo adaptado a su presupuesto.\"",
    brandAmbassador: "— Virat Kohli, Embajador de Marca",
    theFutureOfCommerce: "El Futuro del Comercio",
    askAiAssistant: "Preguntar al Asistente de IA",
    browseCatalog: "Examinar Catálogo",
    exploreModes: "Explorar Modos",
    groupBuyDesc: "Únase a amigos o a la comunidad para desbloquear grandes descuentos al por mayor.",
    liveAuctions: "Subastas en Vivo",
    liveAuctionsDesc: "Puje en tiempo real por artículos exclusivos, raros y de edición limitada.",
    budgetBuilderDesc: "Ingrese su presupuesto y artículos de compra, y deje que la IA cree la mejor combinación.",
    aiSmartMatches: "Coincidencias Inteligentes de IA",
    viewAll: "Ver Todo",
    match: "Coincidencia",
    priceDrops: "Caídas de Precios",
    save: "AHORRA",
    trendingNow: "Tendencias Ahora",
    
    // General UI
    searchPlaceholder: "Buscar productos...",
    addToCart: "Añadir al Carrito",
    buyNow: "Comprar Ahora",
    loading: "Cargando...",
    noProducts: "No se encontraron productos.",
    error: "Ocurrió un error.",
    success: "Éxito",
    placeOrder: "Realizar Pedido",
    subtotal: "Subtotal",
    total: "Total",
    price: "Precio",
    quantity: "Cantidad",
    checkout: "Pagar",
    
    // Login / Register
    email: "Correo Electrónico",
    password: "Contraseña",
    firstName: "Nombre",
    lastName: "Apellido",
    phone: "Teléfono",
    otpCode: "Código OTP",
    sendOtp: "Enviar OTP",
    verifyOtp: "Verificar OTP",
    dontHaveAccount: "¿No tienes una cuenta?",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    
    welcomeBack: "Bienvenido de nuevo",
    signInDesc: "Inicie sesión para continuar en One8 Marketplace",
    unifiedPortal: "Portal Unificado: Iniciamos sesión automáticamente como comprador o vendedor según su cuenta.",
    forgotPassword: "¿Olvidó su contraseña?",
    signUp: "Registrarse",
    createAccount: "Crear cuenta",
    joinMarketplace: "Únase a One8 Marketplace para descubrir y vender productos premium",
    confirmPassword: "Confirmar Contraseña",
    wantTo: "Quiero...",
    shop: "Comprar",
    sell: "Vender",
    verifyEmail: "Verifique su dirección de correo electrónico",
    otpSentText: "Hemos enviado un código de verificación de 6 dígitos a",
    otpVerificationCode: "Código de Verificación OTP",
    resendCode: "Reenviar código",
    resending: "Reenviando...",
    changeEmail: "Cambiar correo electrónico / detalles",
    verifyAndRegister: "Verificar y Registrar",
    sendVerificationOtp: "Enviar OTP de Verificación",
    
    // Cart Page
    yourCart: "Su Carrito",
    cartIsEmpty: "Su carrito está vacío",
    cartEmptyDesc: "Parece que aún no ha añadido ningún artículo premium.",
    startShopping: "Empezar a Comprar",
    orderSummary: "Resumen del Pedido",
    calculatedAtCheckout: "Calculado al pagar",
    proceedToCheckout: "Proceder al Pago",
    
    // Roles / Extra Navigation
    categories: "Categorías",
    addProducts: "Añadir Productos",
    adminPanel: "Panel de Administración",
    footerDesc: "Mercado de lujo impulsado por IA. Curando el futuro del comercio inteligente.",
    footerRights: "© 2026 One8 AI Marketplace. Todos los derechos reservados.",
    sellerDashboard: "Panel de Vendedor",
    myOrders: "Mis Pedidos",
    viewProfile: "Ver Perfil"
  },
  fr: {
    // French
    home: "Accueil",
    cart: "Panier",
    profile: "Profil",
    auctions: "Enchères",
    groupBuy: "Achat Groupé",
    budgetBuilder: "Planificateur de Budget",
    localSellers: "Vendeurs Locaux",
    aiAssistant: "Assistant IA",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    aboutUs: "À Propos de Nous",
    shipping: "Livraison",
    terms: "Conditions d'utilisation",
    privacy: "Politique de Confidentialité",
    partner: "Programme Partenaire",
    
    // Home Page
    heroTitle: "Jouez avec Passion, Achetez avec Intelligence",
    heroSubtitle: "\"Le succès ne se résume pas au travail acharné ; il s'agit de faire des choix intelligents. One8 AI vous propose les meilleurs équipements adaptés à votre budget.\"",
    brandAmbassador: "— Virat Kohli, Ambassadeur de la Marque",
    theFutureOfCommerce: "L'Avenir du Commerce",
    askAiAssistant: "Demander à l'Assistant IA",
    browseCatalog: "Parcourir le Catalogue",
    exploreModes: "Explorer les Modes",
    groupBuyDesc: "Associez-vous à des amis ou à la communauté pour débloquer d'importantes remises de gros.",
    liveAuctions: "Enchères en Direct",
    liveAuctionsDesc: "Enchérissez en temps réel sur des articles exclusifs, rares et en édition limitée.",
    budgetBuilderDesc: "Saisissez votre budget et vos articles, et laissez l'IA créer la meilleure combinaison.",
    aiSmartMatches: "Correspondances Intelligentes IA",
    viewAll: "Voir Tout",
    match: "Correspondance",
    priceDrops: "Baisses de Prix",
    save: "ÉCONOMISER",
    trendingNow: "Tendances Actuelles",
    
    // General UI
    searchPlaceholder: "Rechercher des produits...",
    addToCart: "Ajouter au Panier",
    buyNow: "Acheter Maintenant",
    loading: "Chargement...",
    noProducts: "Aucun produit trouvé.",
    error: "Une erreur est survenue.",
    success: "Succès",
    placeOrder: "Passer la Commande",
    subtotal: "Sous-total",
    total: "Total",
    price: "Prix",
    quantity: "Quantité",
    checkout: "Commander",
    
    // Login / Register
    email: "Adresse E-mail",
    password: "Mot de Passe",
    firstName: "Prénom",
    lastName: "Nom de Famille",
    phone: "Numéro de Téléphone",
    otpCode: "Code OTP",
    sendOtp: "Envoyer OTP",
    verifyOtp: "Vérifier OTP",
    dontHaveAccount: "Vous n'avez pas de compte?",
    alreadyHaveAccount: "Vous avez déjà un compte?",
    
    welcomeBack: "Bon retour",
    signInDesc: "Connectez-vous pour continuer sur One8 Marketplace",
    unifiedPortal: "Portail Unifié: Nous vous connectons automatiquement en tant qu'acheteur ou vendeur en fonction de votre compte.",
    forgotPassword: "Mot de passe oublié ?",
    signUp: "S'inscrire",
    createAccount: "Créer un compte",
    joinMarketplace: "Rejoignez One8 Marketplace pour découvrir et vendre des produits haut de gamme",
    confirmPassword: "Confirmer le mot de passe",
    wantTo: "Je veux...",
    shop: "Acheter",
    sell: "Vendre",
    verifyEmail: "Vérifiez votre adresse e-mail",
    otpSentText: "Nous avons envoyé un code de vérification à 6 chiffres à",
    otpVerificationCode: "Code de vérification OTP",
    resendCode: "Renvoyer le code",
    resending: "Renvoi en cours...",
    changeEmail: "Modifier l'e-mail / les détails",
    verifyAndRegister: "Vérifier et S'enregistrer",
    sendVerificationOtp: "Envoyer l'OTP de vérification",
    
    // Cart Page
    yourCart: "Votre Panier",
    cartIsEmpty: "Votre panier est vide",
    cartEmptyDesc: "Il semble que vous n'ayez pas encore ajouté d'articles premium.",
    startShopping: "Commencer vos achats",
    orderSummary: "Résumé de la commande",
    calculatedAtCheckout: "Calculé lors de la commande",
    proceedToCheckout: "Passer à la caisse",
    
    // Roles / Extra Navigation
    categories: "Catégories",
    addProducts: "Ajouter des Produits",
    adminPanel: "Panneau d'administration",
    footerDesc: "Marché de luxe propulsé par l'IA. Organiser l'avenir du commerce intelligent.",
    footerRights: "© 2026 One8 AI Marketplace. Tous droits réservés.",
    sellerDashboard: "Tableau de Bord Vendeur",
    myOrders: "Mes Commandes",
    viewProfile: "Voir le Profil"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('one8_language') || 'en';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('one8_language', lang);
    }
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
